create table if not exists public.portfolio_settings(id integer primary key check(id=1),profile_url text);insert into public.portfolio_settings(id) values(1) on conflict do nothing;
create table if not exists public.projects(id uuid primary key default gen_random_uuid(),title text not null,description text not null,project_url text,image_url text,sort_order integer default 0,created_at timestamptz default now());
create table if not exists public.certificates(id uuid primary key default gen_random_uuid(),title text not null,issuer text not null,issue_year text,file_url text,created_at timestamptz default now());
alter table public.portfolio_settings enable row level security;alter table public.projects enable row level security;alter table public.certificates enable row level security;
drop policy if exists "public settings" on public.portfolio_settings;drop policy if exists "public projects" on public.projects;drop policy if exists "public certificates" on public.certificates;drop policy if exists "owner settings" on public.portfolio_settings;drop policy if exists "owner project insert" on public.projects;drop policy if exists "owner project update" on public.projects;drop policy if exists "owner project delete" on public.projects;drop policy if exists "owner certificate insert" on public.certificates;drop policy if exists "owner certificate update" on public.certificates;drop policy if exists "owner certificate delete" on public.certificates;
create policy "public settings" on public.portfolio_settings for select to anon,authenticated using(true);create policy "public projects" on public.projects for select to anon,authenticated using(true);create policy "public certificates" on public.certificates for select to anon,authenticated using(true);
create policy "owner settings" on public.portfolio_settings for update to authenticated using((auth.jwt()->>'email')='linkonsen2003@gmail.com');create policy "owner project insert" on public.projects for insert to authenticated with check((auth.jwt()->>'email')='linkonsen2003@gmail.com');create policy "owner project update" on public.projects for update to authenticated using((auth.jwt()->>'email')='linkonsen2003@gmail.com');create policy "owner project delete" on public.projects for delete to authenticated using((auth.jwt()->>'email')='linkonsen2003@gmail.com');create policy "owner certificate insert" on public.certificates for insert to authenticated with check((auth.jwt()->>'email')='linkonsen2003@gmail.com');create policy "owner certificate update" on public.certificates for update to authenticated using((auth.jwt()->>'email')='linkonsen2003@gmail.com');create policy "owner certificate delete" on public.certificates for delete to authenticated using((auth.jwt()->>'email')='linkonsen2003@gmail.com');
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('portfolio-files','portfolio-files',true,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])on conflict(id)do nothing;drop policy if exists "public files" on storage.objects;drop policy if exists "owner file insert" on storage.objects;drop policy if exists "owner file update" on storage.objects;drop policy if exists "owner file delete" on storage.objects;create policy "public files" on storage.objects for select to anon,authenticated using(bucket_id='portfolio-files');create policy "owner file insert" on storage.objects for insert to authenticated with check(bucket_id='portfolio-files' and(auth.jwt()->>'email')='linkonsen2003@gmail.com');create policy "owner file update" on storage.objects for update to authenticated using(bucket_id='portfolio-files' and(auth.jwt()->>'email')='linkonsen2003@gmail.com');create policy "owner file delete" on storage.objects for delete to authenticated using(bucket_id='portfolio-files' and(auth.jwt()->>'email')='linkonsen2003@gmail.com');
grant select on public.portfolio_settings,public.projects,public.certificates to anon;grant select,insert,update,delete on public.portfolio_settings,public.projects,public.certificates to authenticated;
